# configuration for objects and agents, add scene as well
task_name: LiftBarrier
scene:
  name: Robocasa
  env:
    scene_idx: 0
    layout_idx: 3  # 0-9
    style_idx: 3  # 0-11
    customized_layout: configs/robocasa/customized_layout.yaml 
    
objects:
  - name: barrier
    file_path: assets/objects/steel_barrier_annotated/textured.obj
    annotation_path: assets/objects/steel_barrier_annotated/model_data.json
    material: 
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 0.3
        dynamic_friction: 0.3
        restitution: 0.
    visual:
      filename: assets/objects/steel_barrier_annotated/textured.obj
      scale: [0.6, 0.6, 0.2]
    collision:
      type: nonconvex
      filename: assets/objects/steel_barrier_annotated/textured.obj
      scale: [0.6, 0.6, 0.2]
    pos:
      ppos:
        p: [2.4,  -3.375,  0.9270]
        q: [0., 0., 0.]    # not used
      qpos: [0.7320,  0.0070, -0.0090,  0.6810]
      randp_scale: [0.3, 0.05, 0.]
      randq_scale: [0., 0., 0., 0.]
    mass_params:
      mass: 0.1
      cmass_local_pose: [0., 0., 0.]
      inertia: [0., 0.1, 0.]

agents:
  - robot_uid: panda-0
    pos:
      ppos:
        p: [2.55, -4.1, 0.92]
        q: [0., 0., 1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  - robot_uid: panda-1
    pos:
      ppos:
        p: [2.55, -2.6, 0.92]
        q: [0., 0., -1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

cameras:
  sensor:
    - 
      uid: head_camera_agent0
      pose:
        type: look_at
        params: [[2.05, -3.235, 1.32], [2.55, -3.585, 1.02]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.01
      far: 10
    - 
      uid: head_camera_agent1
      pose:
        type: look_at
        params: [[3.05, -3.465, 1.32], [2.55, -3.115, 1.02]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.01
      far: 10

    - 
      uid: head_camera_global
      pose:
        type: pose
        params: [[3.088897, -3.3171689, 1.6619], [0.00132558, -0.278757, 0.00042972, 0.960361]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.01
      far: 10
  human_render:
    - 
      uid: render_camera
      pose:
        type: pose
        params: [[3.02604, -3.60061, 1.6132], [0.175198, -0.26936, 0.0499518, 0.945651]]
      width: 3840
      height: 2160
      fov: 1
      near: 0.01
      far: 1
