# configuration for objects and agents, add scene as well
task_name: PassShoe
scene:
  name: Robocasa
  env:
    scene_idx: 0
    layout_idx: 3  # 0-9
    style_idx: 3  # 0-11
    customized_layout: configs/robocasa/customized_layout.yaml 
  primitives:
    - name: goal_region
      builder: mani_skill.utils.building.actors.build_red_white_target
      params:
        radius: 0.1
        thickness: 0.00005  # 1e-5
        name: goal_region
        add_collision: False
        body_type: kinematic
        initial_pose:
          p: [2.85, -3.05, 0.921]
      pos:
        ppos:
          p: [2.85, -3.05, 0.921]
          q: [0., 1.5707963268, 0.]
        qpos: [0.7071, 0., 0.7071, 0.]
        randp_scale: [0.2, 0.2, 0.]
        randq_scale: [0., 0., 0., 0.]
    
objects:
  - name: shoe
    file_path: assets/objects/single_shoe_annotated/base.glb
    annotation_path: assets/objects/single_shoe_annotated/model_data.json
    material: 
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 0.3
        dynamic_friction: 0.3
        restitution: 0.
    visual:
      filename: assets/objects/single_shoe_annotated/base.glb
      scale: [0.1, 0.1, 0.1]
    collision:
      type: convex
      filename: assets/objects/single_shoe_annotated/base.glb
      scale: [0.1, 0.1, 0.1]
    pos:
      ppos:
        p: [2.25, -3.65, 0.962]
      qpos: [0.055, 0.058, 0.705, 0.705]
      randp_scale: [-0.2, -0.2, 0.]
      randq_scale: [0., 0., 0., 0.]
    mass_params:
      mass: 1
      cmass_local_pose: [0., 0., 0.]
      inertia: [0.1, 0.1, 0.1]

agents:
  - 
    robot_uid: panda-0
    pos:
      ppos:
        p: [2.55, -4.1, 0.92]
        q: [0., 0., 1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  - 
    robot_uid: panda-1
    pos:
      ppos:
        p: [2.55, -2.6, 0.92]
        q: [0., 0., -1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

cameras:
  sensor:
    - 
      uid: head_camera_agent0
      pose:
        type: look_at
        params: [[2.05, -3.235, 1.32], [2.55, -3.585, 1.02]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 10
    - 
      uid: head_camera_agent1
      pose:
        type: look_at
        params: [[3.05, -3.465, 1.32], [2.55, -3.115, 1.02]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 10
    - 
      uid: head_camera_global
      pose:
        type: pose
        params: [[1.851409, -2.915852, 1.478983], [0.954989, 0.038711, 0.144233, -0.256309]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 10
  human_render:
    - 
      uid: render_camera
      pose:
        type: look_at
        params: [[3.15, -2.65, 1.52], [2.55, -3.35, 1.27]]
      width: 1024
      height: 1024
      fov: 1
      near: 0.01
      far: 100
