# configuration for objects and agents, add scene as well
task_name: StrikeCube
scene:
  name: Robocasa
  env:
    scene_idx: 0
    layout_idx: 3  # 0-9
    style_idx: 3  # 0-11
    customized_layout: configs/robocasa/customized_layout.yaml 
  primitives:
    - name: cube
      builder: mani_skill.utils.building.actors.build_cube
      params:
        half_size: 0.02
        color: [0.7333333333, 0.4549019608, 0.6862745098, 1.]
        name: cube
        initial_pose:
          p: [2.65, -3.45, 0.94]
      pos:
        ppos:
          p: [2.65, -3.45, 0.94]
        qpos: [1., 0., 0., 0.]
        randp_scale: [0.05, 0.2, 0.]
        randq_scale: [0., 0., 0., 0.]
        random_quaternions: [1, 1, 0]
    
objects:
  - name: hammer
    file_path: assets/objects/hammer_annotated/base.glb
    annotation_path: assets/objects/hammer_annotated/model_data.json
    material: 
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 0.3
        dynamic_friction: 0.3
        restitution: 0.
    visual:
      filename: assets/objects/hammer_annotated/base.glb
      scale: [0.079, 0.079, 0.079]
    collision:
      type: convex
      filename: assets/objects/hammer_annotated/base.glb
      scale: [0.079, 0.079, 0.079]
    pos:
      ppos:
        p: [2.55, -3.35, 0.962]
      qpos: [0.093, 0.873, 0.476, 0.051]
      randp_scale: [0.06, 0.15, 0.]
      randq_scale: [0., 0., 0., 0.]
    mass_params:
      mass: 0.05
      cmass_local_pose: [0., 0., 0.]
      inertia: [0.1, 0.1, 0.1]

agents:
  - 
    robot_uid: panda-0
    pos:
      ppos:
        p: [1.935, -3.35, 0.92]
        q: [0., 0., 0.]
      qpos: [0., 0.3926990817, 0., -1.5707963268, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

cameras:
  sensor:
    - 
      uid: head_camera
      pose:
        type: look_at
        params: [[2.8, -2.85, 1.32], [2.45, -3.35, 1.02]]
      width: 512
      height: 512
      fov: 1.5707963268
      near: 0.1
      far: 10
  human_render:
    - 
      uid: render_camera
      pose:
        type: look_at
        params: [[3.15, -2.65, 1.52], [2.55, -3.35, 1.27]]
      width: 512
      height: 512
      fov: 1
      near: 0.01
      far: 100
